# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

env:
#  - DISTRO="archlinux/base"
  - DISTRO="debian:sid"
  - DISTRO="fedora:29"
  - DISTRO="ubuntu:18.10"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/pluma
    - enchant
    - file
    - gcc
    - git
    - gobject-introspection
    - gtksourceview3
    - intltool
    - iso-codes
    - itstool
    - libpeas
    - libsm
    - make
    - mate-common
    - python2
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/pluma
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libenchant-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtksourceview-3.0-dev
    - libpeas-dev
    - libsm-dev
    - libx11-dev
    - libxml2-dev
    - make
    - mate-common
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/pluma.git
    - desktop-file-utils
    - enchant-devel
    - gcc
    - git
    - gtk3-devel
    - gtksourceview3-devel
    - iso-codes-devel
    - libSM-devel
    - libpeas-devel
    - make
    - mate-common
    - pygobject3-devel
    - redhat-rpm-config

  ubuntu:
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libenchant-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtksourceview-3.0-dev
    - libpeas-dev
    - libsm-dev
    - libx11-dev
    - libxml2-dev
    - make
    - mate-common
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck
